### ISSUE TITLE
Rubocopを導入する

### ISSUE THREAD

**Issue by sh1nduu** [sh1nduu/Pasokone#10]

**Comment by ykpythemind** [comment]
```
AsciiComments:
  Enabled: false
LineLength:
  Max: 140
Style/FrozenStringLiteralComment:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/FormatString:
  EnforcedStyle: percent
Documentation:
  Enabled: false
Style/Lambda:
  Enabled: false
Rails:
  Enabled: true
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/Documentation:
  Enabled: false
```

自分が使っているrubocop.ymlですが　https://github.com/sh1nduu/Pasokone/pull/9#discussion_r180717921  これでの指摘点のリント入れておいて下さい
